language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up installation of html-proofer
script:
    - bundle exec jekyll build --drafts
    - bundle exec rake test
branches:
  only:
    - gh-pages
