# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Piston
tagline:          A user friendly game engine written in Rust
url:              http://piston.rs
paginate:         1
baseurl:          /
author:
  name:           PistonDevelopers
  url:            http://piston.rs
  email:          contact@piston.rs

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/PistonDevelopers/blog.piston.rs
