# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Piston
tagline:          A modular game engine written in Rust
url:              http://blog.piston.rs
paginate:         3
author:
    name:         PistonDevelopers
    url:          https://github.com/PistonDevelopers
    email:        contact@piston.rs

# Custom vars
version:          1.0.0
github:
    repo:         https://github.com/PistonDevelopers/blog.piston.rs

# Files excluded from site build
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - README.md
    - Rakefile
